"""LOVE STORY — matrix edition. Narration and chapters (original text, no lyrics).

Core_Juliet (white / pale-gold light, the read-only pyramid) and Patch_Romeo (deep blue / silver probe, the sandbox)
inside a rule-bound digital matrix. Easter eggs: port 1989, fearless_mode = true, the single's release date.
"""

# (bar_from, bar_to, Chinese line, small English line)
NARRATION = [
    (0.5, 2.5, '深蓝色的母体。亿万条数据流在总线里穿梭。', 'the matrix: a deep-blue bus hall, data streams everywhere'),
    (2.5, 4.5, '系统已初始化。只读模式已激活。', 'System initialized. Read-only mode activated.'),
    (4.5, 6.5, '高塔之上，Core_Juliet 由纯白与淡金的光粒构成。', 'atop the pyramid: Core_Juliet, white and pale-gold light'),
    (6.5, 8, '她被只读协议永久锁定，只能执行既定的控制流。', 'locked read-only: she may only run the given control flow'),
    (8, 10, '全球数据同步周期开始。例行线程戴着同样的面具。', 'the global sync cycle begins; routine threads wear one mask'),
    (10, 12, 'Patch_Romeo：未签名的开源补丁，伪装成一个无害的 ping。', 'Patch_Romeo: an unsigned patch disguised as a harmless ping'),
    (12, 14, '他穿过拥挤的信道，在中继网关抬头。', 'through the crowded channels he looks up at the relay gateway'),
    (14, 16, '她隔着透明的数据壁垒，看见一道不该存在的蓝光。', 'through the data wall she sees a blue light that should not exist'),
    (16, 18, '两种波长开始共振。', 'two wavelengths begin to resonate'),
    (18, 20, '他发出一缕荧光脉冲。她伸手去碰。', 'he sends a faint pulse; she reaches for it'),
    (20, 22, '未经母体认证的初次握手：SYN，SYN-ACK。', 'an unauthenticated first handshake: SYN, SYN-ACK'),
    (22, 24, '冰冷的只读空间里，第一次泛起金色的涟漪。', 'in the cold read-only space, the first golden ripple'),
    (24, 26, 'Master_Firewall 察觉到异常扰动。', 'Master_Firewall notices an anomaly'),
    (26, 28, '威胁等级在上升。扫描光束开始搜捕。', 'threat level rising; scan beams begin the hunt'),
    (28, 30, '标记：AccessDenied。目标：Patch_Romeo。', 'flagged: AccessDenied. target: Patch_Romeo'),
    (30, 32, '满屏猩红：访问被拒绝。', 'the screen floods red: access denied'),
    (32, 34, '巡逻光束把两人强行分开。', 'patrol beams force the two apart'),
    (34, 36, 'Juliet 被关进高塔的隔离罩。', "Juliet is sealed inside the tower's isolation shield"),
    (36, 38, '她隔着护盾，望向总线尽头那一点蓝。', 'through the shield she watches the blue point at the end of the bus'),
    (38, 40, '每一次鼓点，都是一次锁定。', 'every drum hit is another lock'),
    (40, 42, '夜。母体进入低功耗巡检。', 'night: the matrix drops into low-power patrol'),
    (42, 44, 'Romeo 贴着底层总线，绕过一道道红色巡逻线。', 'Romeo hugs the bottom bus, slipping past the red patrol lines'),
    (44, 46, '他向她的内存端口投出微小的字节序列——像敲窗的小石子。', 'he tosses tiny byte sequences at her memory port, like pebbles on a window'),
    (46, 48, '她收到了。悄悄打开一个未受监控的端口：1989。', 'she receives them and opens an unmonitored port: 1989'),
    (48, 50, '她沿着金字塔的棱线滑下来。', "she slides down the pyramid's edge"),
    (50, 52, '废弃扇区：母体遗忘的空闲内存，长满野草一样的旧代码。', 'the abandoned sector: forgotten memory, overgrown with old code'),
    (52, 54, '两道光并肩走过荧光草地。', 'two lights walk side by side across the glowing field'),
    (54, 56, '没有监控，没有校验，没有只读。', 'no monitor, no checksum, no read-only'),
    (56, 58, '他们在这片混沌里疯狂写入彼此的名字。', "they write each other's names all over the chaos"),
    (58, 60, 'ROMEO。JULIET。ROMEO。JULIET。', 'ROMEO. JULIET. ROMEO. JULIET.'),
    (60, 62, '四周的红色警告开始泛滥。', 'red warnings begin to flood in from the edges'),
    (62, 64, '她看着自己身上越来越不稳的光。', 'she watches her own light grow unstable'),
    (64, 66, '随时可能被终止：SIGKILL。', 'she could be terminated at any moment: SIGKILL'),
    (66, 68, '地下信道被发现了。', 'the hidden channel is found'),
    (68, 70, '红色防线从两侧压过来，警报和鼓点重合。', 'red lines close in from both sides; the alarm lands on the drums'),
    (70, 72, '底层代码像深渊一样把 Romeo 吞了下去。', 'the abyss of low-level code swallows Romeo'),
    (72, 74, '连接丢失。连接丢失。连接丢失。', 'Connection Lost. Connection Lost. Connection Lost.'),
    (74, 76, '深度包检测切断了最后一条链路。', 'deep packet inspection cuts the last link'),
    (76, 78, '他留下一段没写完的校验码，被驱逐到死锁沼泽。', 'he leaves an unfinished checksum and is exiled to the deadlock swamp'),
    (78, 80, '她被重新关进隔离区。', 'she is locked back into isolation'),
    (80, 82, '系统时钟一拍一拍地走。', 'the system clock ticks, beat by beat'),
    (82, 84, '连接超时。连接超时。', 'Connection Timeout. Connection Timeout.'),
    (84, 86.5, '她的粒子开始消散，金色一点点变灰。', 'her particles begin to scatter; the gold turns grey'),
    (86.5, 89, '母体已排程：格式化，写入新的既定框架。', 'the matrix has scheduled a format: a new fixed frame'),
    (89, 91, '代码体出现不可逆的坏道。存活标志位在归零。', 'bad sectors spread; the alive flag counts down to zero'),
    (91, 93, '她以为他已经被内存回收器粉碎。闭上眼睛。', 'she thinks the collector has already erased him; she closes her eyes'),
    (93, 94, '——母体的天空裂开了一道口子。', '— a crack opens across the sky of the matrix'),
    (94, 95, '天空像玻璃一样碎裂。系统重启。', 'the sky shatters like glass; the system reboots'),
    (95, 97, 'Romeo 带着 root 权限的金色光环，逆光破空而来。', 'Romeo descends against the light, crowned with the gold of root'),
    (97, 98, '他没有逃跑。他重写了整个安全框架。', 'he did not run; he rewrote the whole security frame'),
    (98, 100, '所有红色警告，被绿色的 Override Successful 覆盖。', 'every red warning is overwritten by a green Override Successful'),
    (100, 102, '他单膝跪地，掌心是一枚完美哈希凝成的戒指。她点下确认。', 'he kneels with a ring forged from a perfect hash; she confirms'),
    (102, 104, '两串指令冲破边界，化作两道纯白的光柱。', 'two instruction streams break their bounds into two white pillars'),
    (104, 107, '在母体穹顶盘旋，合并为一条永不终结的主分支。', 'spiralling up the dome, they merge into one main branch that never ends'),
    (107, 110, '冰冷的规则世界被漫天的代码花瓣点亮。', 'the cold world of rules lights up with code petals'),
    (110, 113.8, '定格在纯白。', 'held on pure white'),
    (114, 117, '', ''),
    (117, 121, 'return { status: "Happily Ever After" };', '// process exited with code 0.'),
]

CHAPTERS = [(0, '启动'), (8, '01 初见'), (24, '02 阻碍'), (40, '03 幽会'), (56, '04 暴露'), (74, '05 消逝'),
            (94, '06 重写'), (102, '07 合流'), (114, '退出')]
